Add more pre commit hooks
NextCommunity/NextCommunity.github.io pull request #154
Opened 2024-05-26 04:08 UTC by anufdo

Add following pre-commit hooks

- check-json
- check-xml
- detect-private-key
- ruby-validate
- markdownlint
- markdown-link-check

2024-05-26 21:44 UTC, jbampton requested changes
https://github.com/NextCommunity/NextCommunity.github.io/actions/runs/9240519129/job/25420899097?pr=154

2024-05-28 13:50 UTC, anufdo reviewed
Fixed pre commit hooks

2024-05-31 21:54 UTC, anufdo reviewed
Fix broken links and markdown issues.

2024-07-13 13:12 UTC, jbampton approved these changes

2024-07-13 13:12 UTC, merged